# Generated by Django 5.1.7 on 2026-04-14 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('common', '0001_initial'),
        ('tests_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('source_url', models.URLField(blank=True)),
                ('source_domain', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('full_text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/images/')),
                ('day', models.PositiveSmallIntegerField(default=1)),
                ('month', models.PositiveSmallIntegerField(default=1)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('display_date_text', models.CharField(blank=True, max_length=120)),
                ('published_date_at_source', models.DateField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('war', 'Война'), ('birth', 'Рождение'), ('death', 'Смерть'), ('reform', 'Реформа'), ('treaty', 'Договор'), ('culture', 'Культура'), ('discovery', 'Открытие'), ('holiday', 'Праздник'), ('other', 'Другое')], default='other', max_length=32)),
                ('scope', models.CharField(choices=[('russia', 'Россия'), ('world', 'Мир'), ('both', 'Все')], default='both', max_length=16)),
                ('related_topic_text', models.CharField(blank=True, max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('imported_from_historyrussia', models.BooleanField(default=False)),
                ('source_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('raw_payload_json', models.JSONField(blank=True, default=dict)),
                ('raw_html_fragment', models.TextField(blank=True)),
                ('related_materials', models.ManyToManyField(blank=True, related_name='events', to='catalog.material')),
                ('related_tests', models.ManyToManyField(blank=True, related_name='events', to='tests_catalog.testitem')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='common.source')),
                ('tags', models.ManyToManyField(blank=True, related_name='events', to='common.tag')),
            ],
            options={
                'ordering': ['month', 'day', 'title'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_url', ''), _negated=True), fields=('source', 'source_url'), name='unique_event_source_url')],
            },
        ),
    ]
