# Generated by Django 5.1.7 on 2026-04-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_material_is_archived_material_updated_by'),
        ('common', '0001_initial'),
        ('events', '0001_initial'),
        ('tests_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalevent',
            name='canonical_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='event_date_precision',
            field=models.CharField(choices=[('unknown', 'Не определено'), ('day_month', 'День и месяц'), ('day_month_year', 'День, месяц и год')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='first_seen_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='image_url_original',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='import_status',
            field=models.CharField(choices=[('synced', 'Синхронизировано'), ('updated', 'Обновлено'), ('skipped', 'Пропущено'), ('error', 'Ошибка'), ('manual', 'Ручное')], default='synced', max_length=16),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='source_uid',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='historicalevent',
            constraint=models.UniqueConstraint(condition=models.Q(('canonical_url', ''), _negated=True), fields=('source', 'canonical_url'), name='unique_event_source_canonical_url'),
        ),
        migrations.AddConstraint(
            model_name='historicalevent',
            constraint=models.UniqueConstraint(condition=models.Q(('source_uid', ''), _negated=True), fields=('source', 'source_uid'), name='unique_event_source_uid'),
        ),
    ]
