# Generated by Django 5.1.7 on 2026-04-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageAuthorBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_label', models.CharField(default='Автор проекта', max_length=80)),
                ('title_text', models.CharField(default='Автор сайта — Билалова Дина Султановна.', max_length=255)),
                ('subtitle_text', models.CharField(default='Учитель истории и обществознания высшей квалификационной категории, преподаватель СОШИ Лицей имени Н. И. Лобачевского КФУ.', max_length=400)),
                ('description_text', models.TextField(default='Проект объединяет академическую точность, современные учебные маршруты и удобную навигацию по ключевым темам.')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Блок автора на главной',
                'verbose_name_plural': 'Блок автора на главной',
            },
        ),
    ]
