# Generated by Django 5.1.7 on 2026-04-14 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('page_context', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('base_url', models.URLField(blank=True)),
                ('source_type', models.CharField(choices=[('external_education', 'Внешний образовательный'), ('external_library', 'Внешняя библиотека'), ('external_testing', 'Внешнее тестирование'), ('external_calendar', 'Внешний календарь'), ('internal_file', 'Внутренний файл')], default='external_education', max_length=64)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sources/logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('tag_type', models.CharField(choices=[('topic', 'Тема'), ('era', 'Эпоха'), ('region', 'Регион'), ('period', 'Период'), ('format', 'Формат'), ('level', 'Уровень'), ('event_type', 'Тип события'), ('exam_type', 'Тип экзамена'), ('scope', 'Область')], default='topic', max_length=64)),
                ('color', models.CharField(default='#E6E8EE', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExternalClickLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('object_id', models.PositiveIntegerField()),
                ('target_url', models.URLField(max_length=700)),
                ('referrer_path', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
