# Generated by Django 5.1.7 on 2026-04-14 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('short_description', models.TextField(blank=True)),
                ('external_url', models.URLField(blank=True)),
                ('primary_file', models.FileField(blank=True, null=True, upload_to='tests/files/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='tests/covers/')),
                ('exam_type', models.CharField(choices=[('ege', 'ЕГЭ'), ('oge', 'ОГЭ'), ('school_trainer', 'Школьный тренажер'), ('control', 'Контроль знаний'), ('exam', 'Экзамен')], default='school_trainer', max_length=32)),
                ('task_type', models.CharField(choices=[('dates', 'Даты'), ('chronology', 'Хронология'), ('sources', 'Источники'), ('maps', 'Карты'), ('persons', 'Личности'), ('reforms', 'Реформы'), ('wars', 'Войны'), ('terms', 'Термины'), ('mixed', 'Смешанный')], default='mixed', max_length=32)),
                ('difficulty', models.CharField(choices=[('basic', 'Базовый'), ('medium', 'Средний'), ('hard', 'Сложный')], default='medium', max_length=16)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('badge_text', models.CharField(blank=True, max_length=64)),
                ('is_external_resource', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('related_materials', models.ManyToManyField(blank=True, related_name='related_tests', to='catalog.material')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='common.source')),
                ('tags', models.ManyToManyField(blank=True, related_name='tests', to='common.tag')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
