# Generated by Django 5.1.7 on 2026-04-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests_catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testitem",
            name="catalog_section",
            field=models.CharField(
                choices=[("testing", "Тестирования"), ("self_check", "Проверь себя")],
                default="testing",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="testitem",
            name="history_subsection",
            field=models.CharField(
                blank=True,
                choices=[("xvii", "История 17 века"), ("xix", "История 19 века")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="testitem",
            name="subject",
            field=models.CharField(
                choices=[("history", "История"), ("social", "Обществознание")],
                default="history",
                max_length=20,
            ),
        ),
    ]
