# Generated by Django 5.1.7 on 2026-04-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_catalog', '0002_testitem_catalog_section_testitem_history_subsection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testitem',
            name='catalog_section',
            field=models.CharField(choices=[('testing', 'Тестирования'), ('self_check', 'Викторины'), ('activities', 'Мероприятия')], default='testing', max_length=20),
        ),
        migrations.AlterField(
            model_name='testitem',
            name='history_subsection',
            field=models.CharField(blank=True, choices=[('xvii', 'История XVII века'), ('xix', 'История XIX века')], max_length=10),
        ),
    ]
