# Generated by Django 5.1.7 on 2026-05-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_catalog', '0003_alter_testitem_catalog_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testitem',
            name='history_subsection',
            field=models.CharField(blank=True, choices=[('xvi', 'История XVI века'), ('xvii', 'История XVII века'), ('xviii', 'История XVIII века'), ('xix', 'История XIX века'), ('xx', 'История XX века')], max_length=10),
        ),
    ]
