# Generated by Django 5.1.7 on 2026-04-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('short_description', models.TextField(blank=True)),
                ('full_description', models.TextField(blank=True)),
                ('section', models.CharField(choices=[('world', 'Всеобщая история'), ('russia', 'История России')], max_length=32)),
                ('material_kind', models.CharField(choices=[('textbook', 'Учебник'), ('lesson', 'Урок'), ('presentation', 'Презентация'), ('collection', 'Коллекция'), ('pdf', 'PDF'), ('video', 'Видео'), ('image', 'Изображение'), ('article', 'Статья'), ('archive', 'Архив')], default='lesson', max_length=32)),
                ('external_url', models.URLField(blank=True)),
                ('primary_file', models.FileField(blank=True, null=True, upload_to='materials/files/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='materials/covers/')),
                ('badge_text', models.CharField(blank=True, max_length=64)),
                ('level', models.CharField(choices=[('school_basic', 'Школьный базовый'), ('advanced', 'Продвинутый'), ('exam', 'Экзамен'), ('general', 'Общий')], default='general', max_length=32)),
                ('is_external_resource', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('link_priority', models.CharField(choices=[('external', 'Внешняя ссылка'), ('file', 'Локальный файл')], default='external', max_length=16)),
            ],
            options={
                'ordering': ['sort_order', '-published_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MaterialAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/attachments/')),
                ('external_url', models.URLField(blank=True)),
                ('attachment_kind', models.CharField(choices=[('pdf', 'PDF'), ('ppt', 'PPT'), ('pptx', 'PPTX'), ('image', 'Изображение'), ('video', 'Видео'), ('audio', 'Аудио'), ('archive', 'Архив'), ('other', 'Другое')], default='other', max_length=32)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
