# Generated by Django 5.1.7 on 2026-04-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='section',
            field=models.CharField(choices=[('world', 'Всеобщая история'), ('russia', 'История России'), ('social', 'Обществознание')], max_length=32),
        ),
    ]
