# Generated by Django 5.1.7 on 2026-04-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('scope', models.CharField(choices=[('russia', 'Россия'), ('world', 'Мир'), ('both', 'Все')], default='both', max_length=16)),
                ('scale', models.CharField(choices=[('year', 'Год'), ('decade', 'Десятилетие'), ('century', 'Век'), ('era', 'Эпоха')], default='year', max_length=16)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('display_year_text', models.CharField(blank=True, max_length=120)),
                ('is_featured', models.BooleanField(default=False)),
                ('accent_color', models.CharField(default='#915A3B', max_length=20)),
                ('position_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['position_order', 'start_year', 'title'],
            },
        ),
    ]
