# Generated by Django 5.1.7 on 2026-04-14 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('axis', '0001_initial'),
        ('catalog', '0002_initial'),
        ('common', '0001_initial'),
        ('events', '0001_initial'),
        ('tests_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelinenode',
            name='linked_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_nodes', to='events.historicalevent'),
        ),
        migrations.AddField(
            model_name='timelinenode',
            name='linked_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_nodes', to='catalog.material'),
        ),
        migrations.AddField(
            model_name='timelinenode',
            name='linked_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_nodes', to='tests_catalog.testitem'),
        ),
        migrations.AddField(
            model_name='timelinenode',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='timeline_nodes', to='common.tag'),
        ),
    ]
